### ISSUE TITLE
Get verification on Flathub

### ISSUE THREAD

**Issue by rashidi77** [flathub/com.mattjakeman.ExtensionManager#13]
You can now get a 'verified' mark on Flathub beta website. To get this, you have to link your Github source repo in Flathub. It will indicate that the Flatpak is officially maintained.

**Comment by barthalion** [comment]
@mjakeman,

We're preparing for the launch of beta.flathub.org, and would like to see Extensions Manager verified as maintained by its developers. Currently, I've marked it as such manually, but it would be preferred to use one of the verification features. This can be initiated by logging it at https://beta.flathub.org/login with a GitHub account, pressing "Developer Settings" and following the instructions there.

Please let me know when it's done, so I can remove the manual verification flag.

**Comment by mjakeman** [comment]
Hi @barthalion,

I've now verified extension manager against my domain.
